### ISSUE TITLE
<FieldArray> re-renders when it shouldn't

### ISSUE THREAD

**Issue by Dremora** [final-form/react-final-form-arrays#27]
## Bug report

`<FieldArray>` gets re-rendered whenever anything in the form changes, not just the array and its contents.

### What is the expected behavior?

It should work like a regular `<Field>`. That is, only subscribe to changes in the array (and still ignore contents of the array, apart from item additions/removals/reorders.

### Sandbox Link

See https://codesandbox.io/s/yklq254pr1. Open console, add one customer and start editing company name. The whole array will be re-rendered on each key press, as indicate by messages in the console.

### What's your environment?

```
"final-form": "4.5.2",
"final-form-arrays": "1.0.4",
"react-final-form": "3.3.1",
"react-final-form-arrays": "1.0.4",
```

**Comment by erikras** [comment]
Yes. This is one of the perils of render props. To prevent this, you need to provide a `subscription` prop to your `Form`. By default it subscribes to all changes, including changes to `values`, which is what is changing on every keypress. Your form _must_ rerender because the render function you are passing `FieldArray` is instantiated on every render of the form. Every arrow function is created new and is not `===` the previous one.

Your options are:
1. Only subscribe to the flags that you are using in your form's render prop (e.g. `pristine`, `submitting`, etc.). [See this example](https://github.com/final-form/react-final-form#-performance-optimization-through-subscriptions-) (try removing the `subscription` prop and see what happens).
2. Defining your `renderArray` function outside and passing in the same instance of it every time. e.g.
```jsx
const renderArray = ({ fields }) => <div>{fields.map(name => { ... })}</div>

...

<FieldArray name="customers">{renderArray}</FieldArray>
```

Make sense?

**Comment by Dremora** [comment]
I was trying to replicate the issue I've experienced in our application. Looks like I forgot to add subscription to the example app (we actually already use it), and later it turned out all of the dependencies were completely out of date (the [parent sandbox](https://codesandbox.io/s/kx8qv67nk5) from the README should be updated).

Anyway, I've managed to reproduce the issue. See this [codesandbox](https://codesandbox.io/s/yklq254pr1). Add a customer and start typing company name. Messages in the console will be appearing on each keypress. Note that there's a validation function on the first name. It will only succeed once the length of the name is equal to or greater than 3 characters. If you edit first name to satisfy the validation and start editing company name again, nothing will appear in the console.

**Comment by goldins** [comment]
I've been debugging some superfluous rendering and came across this post. It looks like newer versions of react-final-form or -arrays behave differently. I'm not sure if it's a bug, or the code needs to be changed. @erikras I would love some guidance here, as the form I'm having problems with is unusable.

Below are two identical examples using different dependencies (the latter being a slightly modified version of @Dremora's link above)

https://codesandbox.io/s/n42rmx7jnm - minimal re-rendering
```json
{
    "styled-components": "2.2.4",
    "react-final-form-arrays": "1.0.0",
    "react-final-form": "1.1.1",
    "react-dom": "16.2.0",
    "react": "16.2.0",
    "final-form-arrays": "1.0.0",
    "final-form": "1.2.1"
}
```

I modified your example to match the above: https://codesandbox.io/s/oxk5kln6vz - lots of re-rendering
```json
{
    "styled-components": "2.2.4",
    "react-final-form-arrays": "1.0.4",
    "react-final-form": "3.3.1",
    "react-dom": "16.2.0",
    "react": "16.2.0",
    "final-form-arrays": "1.0.4",
    "final-form": "4.5.2"
  }
```
